### ISSUE TITLE
Plugin execution failed on Java 9

### ISSUE THREAD

**Issue by ghost** [mojohaus/rmic-maven-plugin#5]
Hi! I'm trying to build project with rmic-maven-plugin enabled. Plugin execution is successful on JDK 1.6-1.8 but failed on 1.9:
```
[ERROR] Failed to execute goal org.codehaus.mojo:rmic-maven-plugin:1.3:rmic (rmic-process-classes) on project FakeProjectName: Execution rmic-process-classes of goal org.codehaus.mojo:rmic-maven-plugin:1.3:rmic failed: A required class was missing while executing org.codehaus.mojo:rmic-maven-plugin:1.3:rmic: javax/rmi/PortableRemoteObject
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.codehaus.mojo:rmic-maven-plugin:1.3
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/Users/Vladislav_Alekseev/.m2/repository/org/codehaus/mojo/rmic-maven-plugin/1.3/rmic-maven-plugin-1.3.jar
[ERROR] urls[1] = file:/C:/Users/Vladislav_Alekseev/.m2/repository/backport-util-concurrent/backport-util-concurrent/3.1/backport-util-concurrent-3.1.jar
[ERROR] urls[2] = file:/C:/Users/Vladislav_Alekseev/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.11/plexus-interpolation-1.11.jar
[ERROR] urls[3] = file:/C:/Users/Vladislav_Alekseev/.m2/repository/org/codehaus/plexus/plexus-archiver/2.9.1/plexus-archiver-2.9.1.jar
[ERROR] urls[4] = file:/C:/Users/Vladislav_Alekseev/.m2/repository/org/codehaus/plexus/plexus-io/2.4.1/plexus-io-2.4.1.jar
[ERROR] urls[5] = file:/C:/Users/Vladislav_Alekseev/.m2/repository/commons-io/commons-io/2.2/commons-io-2.2.jar
[ERROR] urls[6] = file:/C:/Users/Vladislav_Alekseev/.m2/repository/org/apache/commons/commons-compress/1.9/commons-compress-1.9.jar
[ERROR] urls[7] = file:/C:/Users/Vladislav_Alekseev/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.20/plexus-utils-3.0.20.jar
[ERROR] urls[8] = file:/C:/Users/Vladislav_Alekseev/.m2/repository/org/codehaus/plexus/plexus-compiler-api/2.5/plexus-compiler-api-2.5.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------: javax.rmi.PortableRemoteObject
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:rmic-maven-plugin:1.3:rmic (rmic-process-classes) on project FakeProjectName: Execution rmic-process-classes of goal org.codehaus.mojo:rmic-maven-plugin:1.3:rmic failed: A required class was missing while executing org.codehaus.mojo:rmic-maven-plugin:1.3:rmic: javax/rmi/PortableRemoteObject
-----------------------------------------------------
realm =    plugin>org.codehaus.mojo:rmic-maven-plugin:1.3
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/C:/Users/Vladislav_Alekseev/.m2/repository/org/codehaus/mojo/rmic-maven-plugin/1.3/rmic-maven-plugin-1.3.jar
urls[1] = file:/C:/Users/Vladislav_Alekseev/.m2/repository/backport-util-concurrent/backport-util-concurrent/3.1/backport-util-concurrent-3.1.jar
urls[2] = file:/C:/Users/Vladislav_Alekseev/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.11/plexus-interpolation-1.11.jar
urls[3] = file:/C:/Users/Vladislav_Alekseev/.m2/repository/org/codehaus/plexus/plexus-archiver/2.9.1/plexus-archiver-2.9.1.jar
urls[4] = file:/C:/Users/Vladislav_Alekseev/.m2/repository/org/codehaus/plexus/plexus-io/2.4.1/plexus-io-2.4.1.jar
urls[5] = file:/C:/Users/Vladislav_Alekseev/.m2/repository/commons-io/commons-io/2.2/commons-io-2.2.jar
urls[6] = file:/C:/Users/Vladislav_Alekseev/.m2/repository/org/apache/commons/commons-compress/1.9/commons-compress-1.9.jar
urls[7] = file:/C:/Users/Vladislav_Alekseev/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.20/plexus-utils-3.0.20.jar
urls[8] = file:/C:/Users/Vladislav_Alekseev/.m2/repository/org/codehaus/plexus/plexus-compiler-api/2.5/plexus-compiler-api-2.5.jar
Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

-----------------------------------------------------

	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution rmic-process-classes of goal org.codehaus.mojo:rmic-maven-plugin:1.3:rmic failed: A required class was missing while executing org.codehaus.mojo:rmic-maven-plugin:1.3:rmic: javax/rmi/PortableRemoteObject
-----------------------------------------------------
realm =    plugin>org.codehaus.mojo:rmic-maven-plugin:1.3
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/C:/Users/Vladislav_Alekseev/.m2/repository/org/codehaus/mojo/rmic-maven-plugin/1.3/rmic-maven-plugin-1.3.jar
urls[1] = file:/C:/Users/Vladislav_Alekseev/.m2/repository/backport-util-concurrent/backport-util-concurrent/3.1/backport-util-concurrent-3.1.jar
urls[2] = file:/C:/Users/Vladislav_Alekseev/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.11/plexus-interpolation-1.11.jar
urls[3] = file:/C:/Users/Vladislav_Alekseev/.m2/repository/org/codehaus/plexus/plexus-archiver/2.9.1/plexus-archiver-2.9.1.jar
urls[4] = file:/C:/Users/Vladislav_Alekseev/.m2/repository/org/codehaus/plexus/plexus-io/2.4.1/plexus-io-2.4.1.jar
urls[5] = file:/C:/Users/Vladislav_Alekseev/.m2/repository/commons-io/commons-io/2.2/commons-io-2.2.jar
urls[6] = file:/C:/Users/Vladislav_Alekseev/.m2/repository/org/apache/commons/commons-compress/1.9/commons-compress-1.9.jar
urls[7] = file:/C:/Users/Vladislav_Alekseev/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.20/plexus-utils-3.0.20.jar
urls[8] = file:/C:/Users/Vladislav_Alekseev/.m2/repository/org/codehaus/plexus/plexus-compiler-api/2.5/plexus-compiler-api-2.5.jar
Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

-----------------------------------------------------

	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:168)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 21 more
Caused by: org.apache.maven.plugin.PluginContainerException: A required class was missing while executing org.codehaus.mojo:rmic-maven-plugin:1.3:rmic: javax/rmi/PortableRemoteObject
-----------------------------------------------------
realm =    plugin>org.codehaus.mojo:rmic-maven-plugin:1.3
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/C:/Users/Vladislav_Alekseev/.m2/repository/org/codehaus/mojo/rmic-maven-plugin/1.3/rmic-maven-plugin-1.3.jar
urls[1] = file:/C:/Users/Vladislav_Alekseev/.m2/repository/backport-util-concurrent/backport-util-concurrent/3.1/backport-util-concurrent-3.1.jar
urls[2] = file:/C:/Users/Vladislav_Alekseev/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.11/plexus-interpolation-1.11.jar
urls[3] = file:/C:/Users/Vladislav_Alekseev/.m2/repository/org/codehaus/plexus/plexus-archiver/2.9.1/plexus-archiver-2.9.1.jar
urls[4] = file:/C:/Users/Vladislav_Alekseev/.m2/repository/org/codehaus/plexus/plexus-io/2.4.1/plexus-io-2.4.1.jar
urls[5] = file:/C:/Users/Vladislav_Alekseev/.m2/repository/commons-io/commons-io/2.2/commons-io-2.2.jar
urls[6] = file:/C:/Users/Vladislav_Alekseev/.m2/repository/org/apache/commons/commons-compress/1.9/commons-compress-1.9.jar
urls[7] = file:/C:/Users/Vladislav_Alekseev/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.20/plexus-utils-3.0.20.jar
urls[8] = file:/C:/Users/Vladislav_Alekseev/.m2/repository/org/codehaus/plexus/plexus-compiler-api/2.5/plexus-compiler-api-2.5.jar
Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

-----------------------------------------------------

	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:166)
	... 22 more
Caused by: java.lang.NoClassDefFoundError: javax/rmi/PortableRemoteObject
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1007)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:545)
	at java.base/java.net.URLClassLoader.access$100(URLClassLoader.java:83)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:453)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:447)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:446)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	at org.codehaus.mojo.rmic.AbstractRmiMojo$DependenciesFacadeImpl.loadClass(AbstractRmiMojo.java:575)
	at org.codehaus.mojo.rmic.AbstractRmiMojo.getRemoteClasses(AbstractRmiMojo.java:357)
	at org.codehaus.mojo.rmic.AbstractRmiMojo.doExecute(AbstractRmiMojo.java:275)
	at org.codehaus.mojo.rmic.AbstractRmiMojo.execute(AbstractRmiMojo.java:249)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 22 more
Caused by: java.lang.ClassNotFoundException: javax.rmi.PortableRemoteObject
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 38 more
[ERROR] 
```
Plugin configuration in my pom.xml:
```
 <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>rmic-maven-plugin</artifactId>
                <version>1.3</version>
                <executions>
                    <execution>
                        <id>rmic-process-classes</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>rmic</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                            <sources>
                                <source>
                                    <iiop>true</iiop>
                                    <includes>
                                        <include>**/MyClass.class</include>
                                    </includes>
                                </source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
 <build>
```
Maven 3.5.0, Oracle JDK 9.0.1

**Comment by jpsw** [comment]
Did you find a solution for this?

I get the same error when upgrading from java-8 to java-10.

**Comment by zmlpjuran** [comment]
Same for java-11. But it has bundled rmic. I don't see reason to depend on org.glassfish.corba:rmic.

**Comment by emaysyuk** [comment]
Try adding the following dependency:
```
<dependency>
    <groupId>org.glassfish.corba</groupId>
    <artifactId>glassfish-corba-omgapi</artifactId>
    <version>4.2.0</version>
</dependency>
```

CORBA modules have been [removed from the JDK 11](https://openjdk.java.net/jeps/320).
The transition of stewardship of Java EE from the JCP to the Eclipse Foundation includes [the GlassFish implementation of CORBA and RMI-IIOP](https://github.com/eclipse-ee4j/orb).
